"use client";

import "./globals.css";

import Nav from "@/components/Navigation";

import { ToastContainer, toast } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";

import FinanceContextProvider from "@/lib/store/finance-context";
import AuthContextProvider from "@/lib/store/auth-context";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      

      <head> 
        <title>TrackXpencer</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        
        <link rel="icon"   href="https://static.vecteezy.com/system/resources/thumbnails/005/932/047/small/ex-letters-logo-design-with-purple-blue-colors-and-pine-forest-trees-concept-icon-vector.jpg" />
        </head>
      <body>
        <AuthContextProvider>
          <FinanceContextProvider>
            <ToastContainer />
            <Nav />
            {children}
          </FinanceContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
